# Generated by Django 4.1.7 on 2023-05-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('pin_Code', models.IntegerField()),
                ('Mobile_No', models.IntegerField()),
            ],
        ),
    ]
